FROM  openjdk:17-jdk-slim

RUN mkdir -p /usr/local/wpai/logs/txwx-social-dashboard

WORKDIR /usr/local/wpai

COPY txwx-social-dashboard.jar    txwx-social-dashboard.jar

EXPOSE 9204

CMD ["nohup","java","-jar","/usr/local/wpai/txwx-social-dashboard.jar", ">", "/usr/local/wpai/logs/txwx-social-dashboard/nohup.log", "&"]