-- 修正第一阶段内容表的表注释和字段注释。
-- 仅修正元数据注释，不改变字段类型、索引和业务数据。

USE `ry-cloud2`;

ALTER TABLE content_article
  COMMENT = '内容中心-文章主表',
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '文章ID',
  MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '文章标题',
  MODIFY COLUMN slug VARCHAR(255) NOT NULL COMMENT '文章访问标识',
  MODIFY COLUMN summary VARCHAR(1000) DEFAULT NULL COMMENT '文章摘要',
  MODIFY COLUMN cover_url VARCHAR(1000) DEFAULT NULL COMMENT '封面图URL',
  MODIFY COLUMN author_id BIGINT DEFAULT NULL COMMENT '作者ID',
  MODIFY COLUMN author_name VARCHAR(100) DEFAULT NULL COMMENT '作者名称',
  MODIFY COLUMN content_html LONGTEXT DEFAULT NULL COMMENT 'HTML正文',
  MODIFY COLUMN content_markdown LONGTEXT DEFAULT NULL COMMENT 'Markdown正文',
  MODIFY COLUMN content_json LONGTEXT DEFAULT NULL COMMENT '结构化正文JSON',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT草稿 REVIEWING审核中 PUBLISHED已发布 OFFLINE已下架',
  MODIFY COLUMN visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC' COMMENT '可见性：PUBLIC公开 LOGIN登录可见 PAID付费可见',
  MODIFY COLUMN is_paid CHAR(1) NOT NULL DEFAULT '0' COMMENT '是否付费文章：0否 1是',
  MODIFY COLUMN seo_title VARCHAR(255) DEFAULT NULL COMMENT 'SEO标题',
  MODIFY COLUMN seo_description VARCHAR(500) DEFAULT NULL COMMENT 'SEO描述',
  MODIFY COLUMN seo_keywords VARCHAR(500) DEFAULT NULL COMMENT 'SEO关键词',
  MODIFY COLUMN canonical_url VARCHAR(1000) DEFAULT NULL COMMENT '规范URL',
  MODIFY COLUMN published_at DATETIME DEFAULT NULL COMMENT '发布时间',
  MODIFY COLUMN create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志：0存在 1删除';

ALTER TABLE content_publish_job
  COMMENT = '内容中心-发布任务表',
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发布任务ID',
  MODIFY COLUMN article_id BIGINT NOT NULL COMMENT '文章ID',
  MODIFY COLUMN target_code VARCHAR(64) NOT NULL COMMENT '发布目标编码：SITE_WENDAO WECHAT_OFFICIAL_ACCOUNT等',
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态：PENDING PROCESSING SUCCESS FAILED CANCELLED',
  MODIFY COLUMN scheduled_at DATETIME DEFAULT NULL COMMENT '计划发布时间',
  MODIFY COLUMN started_at DATETIME DEFAULT NULL COMMENT '开始时间',
  MODIFY COLUMN finished_at DATETIME DEFAULT NULL COMMENT '结束时间',
  MODIFY COLUMN operator_id BIGINT DEFAULT NULL COMMENT '操作人ID',
  MODIFY COLUMN operator_name VARCHAR(100) DEFAULT NULL COMMENT '操作人名称',
  MODIFY COLUMN error_message TEXT DEFAULT NULL COMMENT '失败原因',
  MODIFY COLUMN create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志：0存在 1删除';

ALTER TABLE content_publish_result
  COMMENT = '内容中心-发布结果表',
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '发布结果ID',
  MODIFY COLUMN job_id BIGINT NOT NULL COMMENT '发布任务ID',
  MODIFY COLUMN article_id BIGINT NOT NULL COMMENT '文章ID',
  MODIFY COLUMN target_code VARCHAR(64) NOT NULL COMMENT '发布目标编码',
  MODIFY COLUMN external_id VARCHAR(255) DEFAULT NULL COMMENT '外部平台ID',
  MODIFY COLUMN external_url VARCHAR(1000) DEFAULT NULL COMMENT '外部平台URL',
  MODIFY COLUMN site_url VARCHAR(1000) DEFAULT NULL COMMENT '站内URL',
  MODIFY COLUMN payload_json LONGTEXT DEFAULT NULL COMMENT '发布请求快照JSON',
  MODIFY COLUMN result_json LONGTEXT DEFAULT NULL COMMENT '发布结果JSON',
  MODIFY COLUMN create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
  MODIFY COLUMN del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志：0存在 1删除';
