# 基础镜像
FROM  openjdk:17-jdk-slim
# author
MAINTAINER ruoyi

# 挂载目录
VOLUME /home/ruoyi
# 创建目录
RUN mkdir -p /home/ruoyi
# 指定路径
WORKDIR /home/ruoyi
# 复制jar文件到路径
COPY ./jar/txwx-webchatcrm.jar /home/ruoyi/txwx-webchatcrm.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","txwx-webchatcrm.jar"]
