FROM  openjdk:17-jdk-slim

RUN mkdir -p /usr/local/wpai/logs/txwx-social-crm

WORKDIR /usr/local/wpai

COPY txwx-social-crm.jar  txwx-social-crm.jar

EXPOSE 9205

CMD ["nohup","java","-jar","/usr/local/wpai/txwx-social-crm.jar", ">", "/usr/local/wpai/logs/txwx-social-crm/nohup.log", "&"]