-- Database Client 8.4.5
-- Host: 10.0.3.4 Port: 8124 Database: wcai_prod 
-- Dump is still an early version, please use the dumped SQL with caution

CREATE TABLE wcai_prod.article_perday (`ref_date` Date, `user_source` UInt16, `msgid` String, `title` String, `int_page_read_user` UInt16, `int_page_read_count` UInt16, `ori_page_read_user` UInt16, `ori_page_read_count` UInt16, `share_user` UInt16, `share_count` UInt16, `add_to_fav_user` UInt16, `add_to_fav_count` UInt16, `account_id` Int64) ENGINE = MergeTree PARTITION BY toYYYYMMDD(ref_date) ORDER BY ref_date SETTINGS index_granularity = 8192;

CREATE TABLE wcai_prod.dim_age_distribution (`age` String COMMENT '年龄', `user_number` UInt32 COMMENT '用户数', `proportion` String COMMENT '占比', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` Int64 COMMENT '账户ID') ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(pull_time) PRIMARY KEY account_id ORDER BY (account_id, age) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '年龄分布维度表';

CREATE TABLE wcai_prod.dim_channel_composition (`channel` String COMMENT '渠道', `user_number` UInt32 COMMENT '用户数', `proportion` String COMMENT '占比', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` Nullable(Int64)) ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(pull_time) PRIMARY KEY account_id ORDER BY (account_id, channel) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '渠道构成维度表';

CREATE TABLE wcai_prod.dim_sex_distribution (`sex` String COMMENT '性别', `user_number` UInt32 COMMENT '用户数', `proportion` String COMMENT '占比', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` Nullable(Int64)) ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(pull_time) PRIMARY KEY account_id ORDER BY (account_id, sex) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '性别分布维度表';

CREATE TABLE wcai_prod.dim_terrain_distribution (`terrain` String COMMENT '地域位置', `user_number` UInt32 COMMENT '用户数', `proportion` String COMMENT '占比', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` Nullable(Int64)) ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(pull_time) PRIMARY KEY account_id ORDER BY (account_id, terrain) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '地域分布维度表';

CREATE TABLE wcai_prod.dws_article_read (`account_id` UInt64 COMMENT '账户ID', `create_time` Date COMMENT '创建日期', `msgid` String COMMENT '图文消息id', `title` String COMMENT '图文标题', `read_user_total` UInt64 COMMENT '图文页阅读人数', `read_user_source_all` UInt64 COMMENT '全部来源阅读人数', `read_user_source_msg` UInt64 COMMENT '会话阅读人数', `read_user_source_chat` UInt64 COMMENT '好友转发阅读人数', `read_user_source_moments` UInt64 COMMENT '朋友圈阅读人数', `read_user_source_homepage` UInt64 COMMENT '公众号主页阅读人数', `read_user_source_other` UInt64 COMMENT '其他场景阅读人数', `read_user_source_recommend` UInt64 COMMENT '推荐阅读人数', `read_user_source_search` UInt64 COMMENT '搜索阅读人数', `share_user` UInt64 COMMENT '分享人数') ENGINE = MergeTree PARTITION BY toYYYYMMDD(create_time) ORDER BY (account_id, create_time) SETTINGS index_granularity = 8192;

CREATE TABLE wcai_prod.dws_bizsummary_channel_daily (`ref_date` Date COMMENT '日期', `account_id` Int64 COMMENT '账户ID', `channel` String COMMENT '渠道', `read_user_cnt` UInt32 COMMENT '阅读人数', `share_user` UInt32 COMMENT '分享人数', `redirect_ori_page_count` UInt32 COMMENT '阅读原文次数', `redirect_ori_page_user` UInt32 COMMENT '阅读原文人数', `collection_count` UInt32 COMMENT '收藏次数', `collection_user` UInt32 COMMENT '收藏人数', `send_page_count` UInt32 COMMENT '群发篇数', `pull_time` DateTime DEFAULT now() COMMENT '数据插入时间') ENGINE = SummingMergeTree((read_user_cnt, share_user, redirect_ori_page_count, redirect_ori_page_user, collection_count, collection_user, send_page_count)) PARTITION BY toYYYYMM(ref_date) PRIMARY KEY (account_id, ref_date) ORDER BY (account_id, ref_date, channel) SETTINGS index_granularity = 8192 COMMENT '渠道业务日报统计表';

CREATE TABLE wcai_prod.dws_content_data (`title` String, `create_time` DateTime, `latest_stat_date` Date COMMENT '当前这条快照对应的最新统计日', `msgid` String, `author` String, `read_user_total` UInt64, `read_user_source_all` UInt64, `read_user_source_msg` UInt64, `read_user_source_chat` UInt64, `read_user_source_moments` UInt64, `read_user_source_homepage` UInt64, `read_user_source_other` UInt64, `read_user_source_recommend` UInt64, `read_user_source_search` UInt64, `share_user` UInt64, `read_subscribe_user` UInt64, `url` String, `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` UInt64) ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(latest_stat_date) PRIMARY KEY (account_id, latest_stat_date) ORDER BY (account_id, latest_stat_date, msgid, create_time) SETTINGS index_granularity = 8192 COMMENT '内容数据统计表（每日快照）';

CREATE TABLE wcai_prod.dws_users (`ref_date` Date COMMENT '统计日期', `account_id` UInt64 COMMENT '账户ID', `new_user` UInt64 COMMENT '新增用户', `cancel_user` UInt64 COMMENT '注销用户', `net_new_user` UInt64 COMMENT '净增用户', `accumulated_user` UInt64 COMMENT '累计用户') ENGINE = MergeTree PARTITION BY toYYYYMM(ref_date) PRIMARY KEY (account_id, ref_date) ORDER BY (account_id, ref_date) SETTINGS index_granularity = 8192 COMMENT '用户统计事实表';

CREATE TABLE wcai_prod.ods_article (`account_id` UInt64 COMMENT '账户ID', `msgid` String COMMENT '图文消息id', `title` String COMMENT '图文标题', `create_time` Date COMMENT '创建时间', `author` String, `url` String) ENGINE = MergeTree PARTITION BY toYYYYMM(create_time) ORDER BY (account_id, create_time) SETTINGS index_granularity = 8192;

CREATE TABLE wcai_prod.ods_article_detail_daily (`stat_date` Date COMMENT '统计日期', `ref_date` Date COMMENT '参考日期', `msgid` String COMMENT '文章ID', `publish_type` UInt8 COMMENT '发布类型', `read_user` UInt32 COMMENT '阅读用户数', `read_user_source_all` UInt32 COMMENT '全部渠道阅读用户数', `read_user_source_msg` UInt32 COMMENT '消息会话阅读用户数', `read_user_source_chat` UInt32 COMMENT '好友会话阅读用户数', `read_user_source_moments` UInt32 COMMENT '朋友圈阅读用户数', `read_user_source_homepage` UInt32 COMMENT '主页阅读用户数', `read_user_source_other` UInt32 COMMENT '其他渠道阅读用户数', `read_user_source_recommend` UInt32 COMMENT '推荐阅读用户数', `read_user_source_search` UInt32 COMMENT '搜索阅读用户数', `share_user` UInt32 COMMENT '分享用户数', `zaikan_user` UInt32 COMMENT '在看用户数', `like_user` UInt32 COMMENT '点赞用户数', `comment_count` UInt32 COMMENT '评论数', `collection_user` UInt32 COMMENT '收藏用户数', `praise_money` UInt32 COMMENT '赞赏金额', `read_subscribe_user` UInt32 COMMENT '阅读订阅用户数', `read_delivery_rate` Float32 COMMENT '阅读送达率', `read_finish_rate` Float32 COMMENT '阅读完成率', `read_avg_activetime` Float32 COMMENT '阅读平均活跃时间', `update_time` DateTime DEFAULT now() COMMENT '入库时间', `title` String COMMENT '标题', `url` String COMMENT '链接', `account_id` Nullable(Int64) COMMENT '账户ID') ENGINE = ReplacingMergeTree(update_time) PARTITION BY toYYYYMM(stat_date) PRIMARY KEY (account_id, msgid, ref_date) ORDER BY (account_id, msgid, ref_date, stat_date) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '文章每日统计详情表';

CREATE TABLE wcai_prod.ods_article_read_daily (`account_id` UInt64 COMMENT '账户ID', `ref_date` Date COMMENT '数据日期', `msgid` String COMMENT '图文消息id', `read_user_total` UInt32 COMMENT '图文页阅读人数', `read_user_source_all` UInt32 COMMENT '全部来源阅读人数', `read_user_source_msg` UInt32 COMMENT '会话阅读人数', `read_user_source_chat` UInt32 COMMENT '好友转发阅读人数', `read_user_source_moments` UInt32 COMMENT '朋友圈阅读人数', `read_user_source_homepage` UInt32 COMMENT '公众号主页阅读人数', `read_user_source_other` UInt32 COMMENT '其他场景阅读人数', `read_user_source_recommend` UInt32 COMMENT '推荐阅读人数', `read_user_source_search` UInt32 COMMENT '搜索阅读人数', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间') ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(ref_date) ORDER BY (account_id, ref_date, msgid) SETTINGS index_granularity = 8192 COMMENT '文章每日阅读统计表';

CREATE TABLE wcai_prod.ods_article_share_daily (`account_id` UInt64 COMMENT '账户ID', `ref_date` Date COMMENT '统计日期', `msgid` String COMMENT '文章ID', `share_user` UInt32 COMMENT '分享用户数', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间') ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(ref_date) PRIMARY KEY (account_id, ref_date) ORDER BY (account_id, ref_date, msgid) SETTINGS index_granularity = 8192 COMMENT '文章每日分享统计表';

CREATE TABLE wcai_prod.ods_article_summary_daily (`ref_date` Date COMMENT '统计日期', `read_user_total` UInt32 COMMENT '阅读总用户数', `read_user_source_all` UInt32 COMMENT '全部渠道阅读用户数', `read_user_source_msg` UInt32 COMMENT '消息会话阅读用户数', `read_user_source_chat` UInt32 COMMENT '好友会话阅读用户数', `read_user_source_moments` UInt32 COMMENT '朋友圈阅读用户数', `read_user_source_homepage` UInt32 COMMENT '主页阅读用户数', `read_user_source_other` UInt32 COMMENT '其他渠道阅读用户数', `read_user_source_recommend` UInt32 COMMENT '推荐阅读用户数', `read_user_source_search` UInt32 COMMENT '搜索阅读用户数', `share_user` UInt32 COMMENT '分享用户数', `zaikan_user` UInt32 COMMENT '在看用户数', `like_user` UInt32 COMMENT '点赞用户数', `comment_count` UInt32 COMMENT '评论数', `collection_user` UInt32 COMMENT '收藏用户数', `redirect_ori_page_user` UInt32 COMMENT '阅读原文用户数', `send_page_count` UInt32 COMMENT '群发篇数', `pull_time` DateTime DEFAULT now() COMMENT '数据拉取/入库时间', `account_id` Nullable(Int64) COMMENT '账户ID') ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(ref_date) PRIMARY KEY (account_id, ref_date) ORDER BY (account_id, ref_date) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '文章每日汇总统计表';

CREATE TABLE wcai_prod.ods_users (`ref_date` Date COMMENT '统计日期', `user_source` UInt16 COMMENT '用户来源', `new_user` UInt16 COMMENT '新增用户数', `cancel_user` UInt16 COMMENT '取消关注用户数', `account_id` Nullable(Int64) COMMENT '账户ID', `pull_time` DateTime DEFAULT now() COMMENT '数据插入时间') ENGINE = ReplacingMergeTree(pull_time) PARTITION BY toYYYYMM(ref_date) PRIMARY KEY (account_id, ref_date) ORDER BY (account_id, ref_date, user_source) SETTINGS index_granularity = 8192, allow_nullable_key = 1 COMMENT '用户关注趋势统计表';

CREATE TABLE wcai_prod.user_read (`ref_date` Date, `user_source` UInt64, `int_page_read_user` UInt16, `int_page_read_count` UInt16, `ori_page_read_user` UInt16, `ori_page_read_count` UInt16, `share_user` UInt16, `share_count` UInt16, `add_to_fav_user` UInt16, `add_to_fav_count` UInt16, `account_id` Int64) ENGINE = MergeTree PARTITION BY toYYYYMMDD(ref_date) ORDER BY ref_date SETTINGS index_granularity = 8192;